enabled: true
replicas: 1
template:
  podAnnotations: []
  labels: []
image:
  image: ghcr.io/soluto/oidc-server-mock
  imagePullPolicy: Always
  port: 80

resources:
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

nodeSelector: []
affinity: []
tolerations: []
