{{- if $.Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.oidcmock.spec.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels.matchlabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.deployment.podAnnotations }}
      annotations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.matchLabels" $ | nindent 8 }}
    spec:
      imagePullSecrets: {{ include "common.images.renderPullSecrets" (dict "images" (list $.Values.image) "context" $ ) }}
      containers:
        - name: oidc-server-mock
          image: {{ include "common.images.image" (dict "imageRoot" $.Values.image "global" $.Values "chart" $.Chart )}}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: oidc-port
              protocol: TCP
              targetPort: {{ $.Values.dbPort }}
              containerPort: {{ $.Values.dbPort }}
          resources:
            {{- $.Values.resources | toYaml | nindent 12 }}
          env:
            - name: PLACEHOLDER
              value:
                valueFrom:
                  configMapKeyRef:
                    name: oidc-mock-configmap
                    key: env
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- . | toYaml | nindent 10 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- . | toYaml | nindent 10 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- . | toYaml | nindent 10 }}
          {{- end }}
{{- end }}
